### ISSUE TITLE
Error: ForbiddenError: invalid csrf token in apple inbound-auth

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/gluu-passport#169]
Getting below error in **apple** passport social 

```
2020-11-26T11:50:40.518Z [INFO]     Loggers reconfigured
2020-11-26T11:50:40.578Z [INFO]     getTokenEndpoint. Found endpoint at https://gluu.mali.org/oxauth/restv1/token
2020-11-26T11:50:40.612Z [INFO]     getRPT. RPT details were received
2020-11-26T11:50:40.642Z [INFO]     getConfiguration. Passport configs received
2020-11-26T11:50:40.643Z [INFO]     Configuration data has been parsed
2020-11-26T11:50:40.645Z [INFO]     Loggers reconfigured
2020-11-26T11:50:40.646Z [INFO]     Reconfiguring providers
2020-11-26T11:50:40.649Z [INFO]     Setting up strategy for provider p2gluu
2020-11-26T11:50:40.649Z [INFO]     Loading node strategy module passport-openidconnect
2020-11-26T11:50:40.653Z [INFO]     Setting up strategy for provider apple
2020-11-26T11:50:40.654Z [INFO]     Loading node strategy module @nicokaiser/passport-apple
2020-11-26T11:50:40.658Z [INFO]     Server listening on https://gluu.mali.org:8090
2020-11-26T11:51:40.651Z [INFO]     getConfiguration. Passport configs received
2020-11-26T11:51:40.652Z [INFO]     Response received
2020-11-26T11:51:40.653Z [INFO]     Configuration data has been parsed
2020-11-26T11:51:44.274Z [INFO]     ::1 - GET /passport/token HTTP/1.1 200 201 - 6.811 ms
2020-11-26T11:51:44.283Z [INFO]     ::1 - GET /passport/auth/apple/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3QiOiI0MTQ0MmMyYy1hYjBmLTRhMDEtYjQyMS1jZjc4MWU0NzkwOTUiLCJpYXQiOjE2MDYzOTE1MDQsImV4cCI6MTYwNjM5MTYyNH0.6xQcs7Se2_PpDkWpmcUZRx_MuV6elDrF9KlzFFDpn6I HTTP/1.1 302 0 - 3.853 ms
2020-11-26T11:52:00.790Z [ERROR]    Unknown Error: ForbiddenError: invalid csrf token
2020-11-26T11:52:00.790Z [ERROR]    ForbiddenError: invalid csrf token
    at csrf (/home/kd/Documents/GLUU/gluu-passport/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:317:13)
    at /home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/home/kd/Documents/GLUU/gluu-passport/node_modules/cookie-parser/index.js:71:5)
    at Layer.handle [as handle_request] (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:317:13)
    at /home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:275:10)
    at /home/kd/Documents/GLUU/gluu-passport/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/kd/Documents/GLUU/gluu-passport/node_modules/raw-body/index.js:224:16)
    at done (/home/kd/Documents/GLUU/gluu-passport/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/kd/Documents/GLUU/gluu-passport/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)
2020-11-26T11:52:00.791Z [INFO]     ::1 - POST /passport/auth/apple/callback HTTP/1.1 500 148 - 20.037 ms
2020-11-26T11:52:40.676Z [INFO]     getConfiguration. Passport configs received
2020-11-26T11:52:40.677Z [INFO]     Response received
2020-11-26T11:52:40.678Z [INFO]     Configuration data has been parsed
```

How to reproduce:
1. Add apple provider
2. Enable passport-social
3. Try to login with apple
4. when we get back to passport after apple auth, passport throwing above error

Note: I've tested with oidc, not getting problem. Getting problem in apple case. Not sure about google.

**Comment by christian-hawk** [comment]
I just did a test with passport-saml, same happens
```bash
2020-11-27T01:18:05.493Z [ERROR]    Unknown Error: ForbiddenError: invalid csrf token
2020-11-27T01:18:05.494Z [ERROR]    ForbiddenError: invalid csrf token
    at csrf (/opt/gluu/node/passport/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/opt/gluu/node/passport/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/gluu/node/passport/node_modules/express/lib/router/index.js:317:13)
    at /opt/gluu/node/passport/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/gluu/node/passport/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/gluu/node/passport/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/opt/gluu/node/passport/node_modules/cookie-parser/index.js:71:5)
    at Layer.handle [as handle_request] (/opt/gluu/node/passport/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/gluu/node/passport/node_modules/express/lib/router/index.js:317:13)
    at /opt/gluu/node/passport/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/gluu/node/passport/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/gluu/node/passport/node_modules/express/lib/router/index.js:275:10)
    at /opt/gluu/node/passport/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/opt/gluu/node/passport/node_modules/raw-body/index.js:224:16)
    at done (/opt/gluu/node/passport/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/opt/gluu/node/passport/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-11-27T01:18:05.495Z [INFO]     ::1 - POST /passport/auth/saml/saml-default/callback HTTP/1.1 500 148 - 14.228 ms
```

Gonna R&D
