### ISSUE TITLE
Overall logging enhancements

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#33]
In this issue I will list improvements related to logging (applicable for any passport-related repo). There are some logging-issues already opened (eg #32, #25). but  I would like to have all new ones here.

You can add your own ideas/needs  in this issue

We should:

- use a daily log (currenlty a new one created every hour) [**DONE**]
- Not printing the whole `EntityDescriptor` tag for saml IDPs (`saml.js`). At least not in INFO level [**DONE**]
- Promote `silly` to `debug`, `debug` to `verbose`, etc.. [**DONE**]
- Wrap in a single function the call to winston and MQ logger [**DONE**]

**Comment by jgomer2001** [comment]
Errors sometimes logged this way:

```
2018-08-07T00:50:30+0000 [ERROR] uncaughtException: Cannot read property 'authenticate' of undefined
	{"date":"Tue Aug 07 2018 00:50:30 GMT+0000 (UTC)","process":{"pid":7690,"uid":495,"gid":495,"cwd":"/home/node","execPath":"/opt/node-v9.9.0-linux-x64/bin/node","version":"v9.9.0","argv":["/opt/node-v9.9.0-linux-x64/bin/node","/opt/gluu/node/passport/server/app.js","start-log-file=/opt/gluu/node/passport/server/logs/start.log"],"memoryUsage":{"rss":58392576,"heapTotal":60649472,"heapUsed":24979624,"external":170712}},"os":{"loadavg":[0,0.00244140625,0.0517578125],"uptime":1386},"trace":[{"column":22,"file":"/opt/gluu/node/passport/server/routes/index.js","function":null,"line":273,"method":null,"native":false},{"column":30,"file":"module.js","function":"Module._compile","line":649,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Module._extensions..js","line":660,"method":".js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":561,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":501,"method":null,"native":false},{"column":3,"file":"module.js","function":"Module._load","line":493,"method":"_load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":593,"method":"require","native":false},{"column":18,"file":"internal/module.js","function":"require","line":11,"method":null,"native":false},{"column":22,"file":"/opt/gluu/node/passport/server/app.js","function":null,"line":90,"method":null,"native":false},{"column":30,"file":"module.js","function":"Module._compile","line":649,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Module._extensions..js","line":660,"method":".js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":561,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":501,"method":null,"native":false},{"column":3,"file":"module.js","function":"Module._load","line":493,"method":"_load","native":false},{"column":10,"file":"module.js","function":"Module.runMain","line":690,"method":"runMain","native":false},{"column":16,"file":"bootstrap_node.js","function":"startup","line":194,"method":null,"native":false},{"column":3,"file":"bootstrap_node.js","function":null,"line":666,"method":null,"native":false}],"stack":["TypeError: Cannot read property 'authenticate' of undefined","    at Object.<anonymous> (/opt/gluu/node/passport/server/routes/index.js:273:22)","    at Module._compile (module.js:649:30)","    at Object.Module._extensions..js (module.js:660:10)","    at Module.load (module.js:561:32)","    at tryModuleLoad (module.js:501:12)","    at Function.Module._load (module.js:493:3)","    at Module.require (module.js:593:17)","    at require (internal/module.js:11:18)","    at Object.<anonymous> (/opt/gluu/node/passport/server/app.js:90:22)","    at Module._compile (module.js:649:30)","    at Object.Module._extensions..js (module.js:660:10)","    at Module.load (module.js:561:32)","    at tryModuleLoad (module.js:501:12)","    at Function.Module._load (module.js:493:3)","    at Function.Module.runMain (module.js:690:10)","    at startup (bootstrap_node.js:194:16)","    at bootstrap_node.js:666:3"]}
```

It suffices (and would be neater) this way:

```
    TypeError: Cannot read property 'authenticate' of undefined
        at Object.<anonymous> (/opt/gluu/node/passport/server/routes/index.js:273:22)
        at Module._compile (module.js:649:30)
        at Object.Module._extensions..js (module.js:660:10)
        at Module.load (module.js:561:32)
        at tryModuleLoad (module.js:501:12)
        at Function.Module._load (module.js:493:3)
        at Module.require (module.js:593:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/opt/gluu/node/passport/server/app.js:90:22)
        at Module._compile (module.js:649:30)
        at Object.Module._extensions..js (module.js:660:10)
        at Module.load (module.js:561:32)
        at tryModuleLoad (module.js:501:12)
        at Function.Module._load (module.js:493:3)
        at Function.Module.runMain (module.js:690:10)
        at startup (bootstrap_node.js:194:16)
        at bootstrap_node.js:666:3
```

**Comment by jgomer2001** [comment]
closign this, more logging issues appeared
