### ISSUE TITLE
Cannot find module 'config'

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#99]
In latest 4.2 beta,upon start passport throws:

```
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'config'
Require stack:
- /opt/gluu/node/passport/server/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/opt/gluu/node/passport/server/app.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/gluu/node/passport/server/app.js' ]
}
```
```
[root@c2 upg]# ls /opt/gluu/node/passport
config  LICENSE  logs  node_modules  package.json  package-lock.json  README.md  server  test
```

**Comment by jgomer2001** [comment]
@mbaser 

@christian-hawk and @mbaser 
we should not change the way setup.py installs (post-installs) passport by now (this is not a good moment). I think having an static tarball has to do with customer environments without internet  connectivity, however, upon linux package installation  setup.py is deing ownloaded from github.... We can discuss later with @yurem why we use the node-modules tarball instead of npm install. 

@mbaser 

>  node_modules package name was changed

can you describe what was the change?

**Comment by christian-hawk** [comment]
@jgomer2001 agree completely with you. Thanks

**Comment by christian-hawk** [comment]
@mbaser anyway I gonna look into it, I need you to provide information to reproduce.

- Former version installed off gluu-server
- how `node_modules` package was generated (downloaded from maven, build locally...?)
- npm version where package was generated

Thanks

**Comment by christian-hawk** [comment]
@mbaser @jgomer2001 

I installed the passport 4.2.0 in gluu-server 4.1 and works.
@mbaser please follow this steps:

1. 4.1 fresh install
2. `service passport stop`
3. moved `/opt/gluu/node/passport` to `/opt/gluu/node/passport.backup`
4. downloaded and unpacked passport 4.2 tgz `tar --strip 1 -xzf passport-4.2.0.tgz -C ./passport --no-xattrs --no-same-owner --no-same-permissions`
5. downloaded and unpacked passport 4.2 modules tgz
6. updated `/etc/default/passport` with correct variables (please see below)
7. mkdir /opt/gluu/node/passport/logs
8. passport service start
9. All working:

```
2020-07-12T20:51:28.349Z [INFO]     Loggers reconfigured
2020-07-12T20:51:28.533Z [INFO]     getTokenEndpoint. Found endpoint at https://centos41.techno24x7.com/oxauth/restv1/token
2020-07-12T20:51:28.581Z [INFO]     getRPT. RPT details were received
2020-07-12T20:51:28.625Z [INFO]     getConfiguration. Passport configs received
2020-07-12T20:51:28.625Z [INFO]     Configuration data has been parsed
2020-07-12T20:51:28.627Z [INFO]     Loggers reconfigured
2020-07-12T20:51:28.627Z [INFO]     Reconfiguring providers
2020-07-12T20:51:28.630Z [INFO]     Server listening on https://centos41.techno24x7.com:8090
[root@centos41 passport]# 
```

**passport config file:** `/etc/default/passport`
```
NODE_HOME=/opt/node
NODE=$NODE_HOME/bin/node
NODE_BASE=/opt/gluu/node/passport
NODE_LOGS=${NODE_BASE}/logs
NODE_APP=server/app.js
NODE_OPTIONS="PORT=8090 NODE_ENV=production HOSTNAME=localhost"
NODE_ARGS="--max-old-space-size=558"
APP_ARGS=""
NODE_USER=node
TMPDIR=/opt/node/temp

```

**Comment by christian-hawk** [comment]
worth to mention:
`npm install --production`:

1. will check if all the node modules are into `/node_modules` folder
2. if they are, they will **not** be downloaded
3. if there is some package missing, and computer is **offline** it **throws error** (good to check with install script)
4. if there is some package missing, and computer is **online** it download the missing packages

**Comment by mbaser** [comment]
Using this package https://ox.gluu.org/npm/passport/passport-master-node_modules.tar.gz solved the issue.
Actually there was no issue, both packager and upgrade script was using wrong package.
